name: EliteIPA
options:
  bundleId: com.elite.ipa
  deploymentTarget:
    iOS: 15.0

targets:
  EliteIPA:
    type: application
    platform: iOS
    sources:
      - path: .
        includes:
          - "*.swift"
          - "*.h"
          - "*.cpp"
          - "*.entitlements"
          - "Info.plist"
    info:
      path: Info.plist
